discordclient:
    id: "abc"

db:
    init: true

spring:
    datasource:
        url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
        username: "sa"
        password: "sa"
    jpa:
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true