discordclient:
    id: ""

spring:
    datasource:
        url: ""
        username: ""
        password: ""
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true