CREATE TABLE CHANNEL_T01
(
    OID         BIGINT UNSIGNED PRIMARY KEY,
    ServerOID   BIGINT UNSIGNED,
    Channelname VARCHAR(30),
    CONSTRAINT FK_ServerOID FOREIGN KEY (ServerOID) REFERENCES SERVER_T01 (OID)
);