CREATE TABLE IF NOT EXISTS DATAMODEL_CHECKPOINT_T01
(
    OID           BIGINT PRIMARY KEY,
    ScriptOID     VARCHAR(50),
    ExecutionTime TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS DATAMODEL_CHECKPOINT_Q01;